// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bfmpalovrbstmuvlsxsp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJmbXBhbG92cmJzdG11dmxzeHNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5MDAyODMsImV4cCI6MjA3NDQ3NjI4M30.jn79XxgveiJDbrd8vONttOCl_KniqkZakz4mfKo-s8k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});